---
apiVersion: v1
kind: Pod
metadata:
  name: worker
spec:
  containers:
    - name: build
      image: "{{ images.build }}"
      resources:
        requests:
          cpu: "250m"
          memory: 1Gi
        limits:
          cpu: "1"
          memory: 1Gi
      volumeMounts:
        - name: worker-workspace
          mountPath: /workdir
  volumes:
    - name: worker-workspace
      emptyDir: {}
