---
version: '0.2'

branches:
  default:
    stage: pre-merge

models:
  - env: &coverage
      CODECOV_TOKEN: '%(secret:codecov_token)s'
      VCS_COMMIT_ID: '%(prop:revision)s'
      VCS_BRANCH_NAME: '%(prop:branch)s'
      CI_BUILD_ID: '%(prop:bootstrap)s'

stages:
  pre-merge:
    worker:
      type: kube_pod
      path: eve/workers/pod.yaml
      images:
        build: eve/workers/build
    steps:
      - Git: &git_pull
          name: git pull
          repourl: "%(prop:git_reference)s"
          shallow: true
          retryFetch: true
          haltOnFailure: true
      - ShellCommand:
          name: gradle build
          command: gradle build
      - ShellCommand:
          name: upload test coverage
          haltOnFailure: False
          command: "curl -s https://codecov.io/bash | bash"
          env:
            <<: *coverage
      - Upload:
          name: Upload reports
          source: 'reports'
          urls:
            - 'pmd-lint/*.html' # this will create links to every .html files
            - 'spotbugs/*.html'
            - 'code-coverage/*.html'
