name: test-and-build

on:
  push:
    branches-ignore:
      - development/**
      - main/**
      - q/*/**

jobs:
  gradle_build_and_upload:
    name: Gradle build and upload snapshot
    uses: ./.github/workflows/gradle_build_and_upload.yml
    secrets: inherit

  code_coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          name: codecov-vaultclient-java
