name: release-to-Nexus-Release-Repository

on:
  workflow_dispatch:

jobs:
  gradle_build_and_upload:
    name: Gradle build and upload release
    uses: ./.github/workflows/gradle_build_and_upload.yml
    secrets: inherit
    with:
      release: true
